# Generated by Django 5.2.6 on 2025-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizgen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ai_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for AI generation', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ai_topic',
            field=models.CharField(blank=True, help_text='Topic used for AI generation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store AI generation details'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
